# Generated by Django 5.1.1 on 2024-10-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogapi', '0003_category_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Коммент_Создал', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Комментарии', to='blogapi.post')),
            ],
        ),
    ]
